### ISSUE TITLE
bundle.js is missing in /src/js-dependency/out/core

### ISSUE THREAD

**Issue by HunteRoi** [PejmanNik/puppeteer-report-csharp#1]
There is no bundle.js when we follow the steps designed in your README. 

It seems like the shell script runs into an error and closes right away, not telling anything to the user. This is not user-friendly. 

Do you have a plan to fix this? I think this might be related to the issue described on your js repository: https://github.com/PejmanNik/puppeteer-report/issues/27

**Comment by PejmanNik** [comment]
Yes, I agree. I think it is because the base package updated and the process has been broken; I'll fix it on the weekend.

**Comment by PejmanNik** [comment]
The issue was in updating the `puppeteer-report` as a submodule. it is fixed now in version 3.0.2
